# Generated by Django 3.2.7 on 2021-09-15 17:33

import authors.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20210915_1719'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myusermodel',
            managers=[
                ('objects', authors.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='myusermodel',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
