# Generated by Django 3.2.7 on 2021-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
